### ISSUE TITLE
unexpected behaviour when clicking on arrow glyphicons 

### ISSUE THREAD

**Issue by qexpres** [2amigos/yii2-date-time-picker-widget#10] opened 2015-07-06 11:07 UTC
Whenever you want to click on a glyphicon arrow, the picker goes to the next, more fine-grained, view. For instance, while in month view. If you click on either one of glyphicon arrows, it automatically goes to the day view. This does not happen when you click on the button, but not the glyphicon itself.

Tested with Chrome 43.0.2357.130 (64-bit) on OS X.

**Comment by madeadi** [comment] 2015-07-22 07:44
I encountered the same issue, in which if I click left/right, it will go to a finer view, i.e. from month view to date view. 

I thought it was random until @qexpres wrote about it above. This issue only happens if I click the glyphicon.

**Comment by bfday** [comment] 2016-01-13 05:36
Yeap, the problem stood still. Any fixes?

**Comment by drishu** [comment] 2016-04-23 15:03
Same for me, no matter what browser

**Comment by tonydspaniard** [comment] 2017-07-05 05:57
@qexpres the problem is with the `bootstrap-datetimepicker` plugin itself. This issue is quite old (sorry for being unresponsive) so I am going to close it.

I cannot replicate it either. Let me know if it still happening and a snapshot how to replicate it. Thanks.

**Closed by tonydspaniard** 2017-07-05 05:57 UTC
